### ISSUE TITLE
Change shortcut

### ISSUE THREAD

**Issue by mBouamama** [tmbo/questionary#102]
Hi,
I use `rawselect`:
```
test = questionary.rawselect(
      "What do you want to do?",
      choices=["Order a pizza", "Make a reservation", "Ask for opening hours"],
  ).ask()
```
How can i change shortcut for changing my choice? By default it's 1,2,3 but i want to use ⬆⬇
Regards.

**Comment by kiancross** [comment]
@mBouamama You'd be better of using a [`select`](https://questionary.readthedocs.io/en/stable/pages/types.html#select) instead.

**Comment by mBouamama** [comment]
thx
