### ISSUE TITLE
ANSI colours for prompt title

### ISSUE THREAD

**Issue by ewels** [tmbo/questionary#107]
Hi there,

Is it possible to give colours and formatting using ANSI codes to a questionary prompt title?

I am using the following code to generate prompts:

```python
questionary.Choice(title=nice_title, value=raw_value)
```

I show the default value and other helpful information in the `nice_title` which is not passed through to the underlying response. This works brilliantly - I'd just like to be able to add some formatting to this.

### Manual ANSI codes

I've tried manually adding ANSI codes to the string, or using libraries like [`rich`](https://github.com/willmcgugan/rich) but they are escaped and don't work:

```
myval  ^[[1;3;31m(False)^[[0m
```

Where I would like:
```
myval  (False)
```
..with `(False)` in bold-red text in this example.

#### Prompt toolkit

I dug around in the Questionary codebase a little and found that the `title` attribute is of class `FormattedText`, which is defined here:

https://github.com/tmbo/questionary/blob/11ceb8e270457113eb40ef1603fbd888ef500b5e/questionary/prompts/common.py#L23-L30

I feel like this is maybe getting close to something I could use, but I pretty much hit a wall at that point. I tried a bit of trial and error with passing lists of strings with stuff like `class:selected` but succeeded only in breaking stuff. Also I want to format only a partial section of the string so I'm not sure that this would work.

Any tips or pointers on how I might be able to achieve this?

Many thanks in advance,

Phil

**Comment by kiancross** [comment]
Hi Phil,

You're very close with `FormattedText`. I think this should do what you want:

```python3
import questionary

style = questionary.Style([
                     #fg:red <- These two are equivalent
    ("choice-title", "fg:#f00 bold"),
])

questionary.select("Choose something", [
    questionary.Choice(
        title=[("", "myval "), ("class:choice-title", "(false)")],
        value="myval",
    )
], style=style).ask()
```

**Comment by ewels** [comment]
Ah fantastic - thank you so much! I've been fighting on and off with this for a while now, your little example brings it all together!

Implemented and working great in no time once I had that pattern. Thank you!
