### ISSUE TITLE
Suggest relaxing Python version constraint

### ISSUE THREAD

**Issue by layday** [tmbo/questionary#109]
Seeing as this is a pure Python package, would you consider relaxing the Python version constraint so that it at least allows for the package to be used with the next Python version?   Packages which depend on Questionary could then be tested with Python pre-releases without having to pass `--ignore-requires-python` to pip.

**Comment by tmbo** [comment]
@layday that is a good point :+1: let's do that. do you mind creating a PR?

**Comment by layday** [comment]
With the release of Python 3.10 approaching, would it be possible to release a new version with the constraint lifted?

**Comment by kiancross** [comment]
> With the release of Python 3.10 approaching, would it be possible to release a new version with the constraint lifted?

I'll try to sort out a couple of the PRs first - but at the latest, I'll create a new release at the end of this week.

**Comment by layday** [comment]
Thanks!

**Comment by kiancross** [comment]
@layday FYI new version is now released: https://pypi.org/project/questionary/1.10.0/.
