### ISSUE TITLE
Hidden and Blink prompt style flags have no effect

### ISSUE THREAD

**Issue by BradenM** [tmbo/questionary#11]
Hi,

I use questionary in several of my projects (thanks for that, it's a great prompt library!) and have found an issue when styling the prompts. 

It seems that that passing the `hidden` or `blink` flags to `prompt_toolkit.styles.Style` has no effect. (See docs of the flags I'm referring too [here](https://python-prompt-toolkit.readthedocs.io/en/2.0.7/pages/advanced_topics/styling.html)) 

See this example code:
```
python: 3.7.3
questionary: 1.1.1
prompt_toolkit: 2.0.9
```

```python
import questionary as prompt
from prompt_toolkit.styles import Style

custom_style_fancy = Style([
    ('qmark', 'fg:#673ab7 reverse'),    # Reverse appears to work
    ('question', 'hidden'),  # Hidden Not working
    ('answer', 'fg:#f44336 bold'),
    ('pointer', 'fg:#673ab7 hidden'),  # Not working with color
    ('selected', 'fg:#cc5454 blink'),  # Not working
    ('separator', 'fg:#cc5454'),
    # Not working
    ('instruction', 'hidden')
])

check_box = prompt.checkbox(
    "Title", ["Choice 1", "Choice 2", "Choice 3"], style=custom_style_fancy)
c_result = check_box.ask()

text = prompt.text("A Question", style=custom_style_fancy)
t_result = text.ask()

print("Results:", c_result, t_result)
```

See results:
![questionary_issue](https://user-images.githubusercontent.com/5913808/61852310-cf631400-ae7e-11e9-8576-fe61af470abe.gif)

I'm happy to provide any other info/help you need.

**Comment by tmbo** [comment]
very good point, I actually haven't tested them myself but will try to look into this. I guess you are trying to use `hidden` to get rid of the question prefix?

**Comment by BradenM** [comment]
Actually the checkbox instructions, wanted to put them on a separate line. But same idea.

**Comment by kiancross** [comment]
@BradenM Is this fixed now? I tried your example and it seemed to be behaving as expected? Might have been fixed by the `prompt_toolkit` project.

**Comment by BradenM** [comment]
👍 Can confirm, works as intended now. Thanks
