### ISSUE TITLE
[IMP] Multiline instruction by changing to Finish with 'Alt+Enter' or 'Esc THEN Enter'

### ISSUE THREAD

**Issue by bosd** [tmbo/questionary#114]
Suggestion to make the multi-line instruction more clear by changing from:
`(Finish with 'Alt+Enter' or 'Esc, Enter')\n>`
to
 `(Finish with 'Alt+Enter' or 'Esc then Enter')\n>`

in 
https://github.com/tmbo/questionary/blob/11ceb8e270457113eb40ef1603fbd888ef500b5e/questionary/constants.py#L16

**Comment by tmbo** [comment]
great suggestion, do you mind proposing a pull request to fix it?

**Comment by bosd** [comment]
Opened a PR.
Item was discussed in https://github.com/copier-org/copier/issues/344#issuecomment-775332811 

Will open a PR as well on my highly opinionated pointer 👉, to improve readability on High-res displays.
(will see if there is interest to get it merged)
