### ISSUE TITLE
Any support for editor question type similar to pyinquirer?

### ISSUE THREAD

**Issue by info-rchitect** [tmbo/questionary#119]
Hi,

I have a use-case where I want the user to enter N lines of SQL.  Are there any plans to add an editor mode similar to PyInquirer?

thx!

**Comment by kiancross** [comment]
That would be a nice feature to add - will leave this open as a feature request.

Does using a `multiline` [`Text`](https://questionary.readthedocs.io/en/stable/pages/types.html#text) input help at all in the meantime?

**Comment by info-rchitect** [comment]
@kiancross Yes multiline worked fine for me, thx

**Comment by kiancross** [comment]
Closing as already implemented using the `multiline` option.
