### ISSUE TITLE
Allow start point of file path to be specified

### ISSUE THREAD

**Issue by marmstr93ng** [tmbo/questionary#120]
Is there a way to specify a predefined start point when using the File Path type? For example, the user should always begin at 'C:\Users\x.xxxx\Documents' and navigates from there.

Thanks!

**Comment by kiancross** [comment]
You might be able to use a combination of the `validate` and `file_filter` options (see [here](https://questionary.readthedocs.io/en/stable/pages/types.html#file-path)) to get something close to this.

**Comment by marmstr93ng** [comment]
Yes, I looked into both of these options but as far as I can tell that solution still requires the user to type in the path from the beginning (requiring knowledge of the path's existence). A workaround is to include the start portion of the path in the question that the user then copies (it's a bit of hack). The File Path question type has no instruction parameter so including it in the question was the only option for this.

**Comment by kiancross** [comment]
I've added the enhancement tag, as this would be a nice feature to have!

**Comment by WilliamStam** [comment]
just incase this might help (or help others)..

what you could maybe consider doing is something like:
```
select folder?
- use this folder
- folder 1
- folder 2
```
if you select folder 2 it then appends it to the "folder" path (from where you start) every time you select a folder so like find folders in "current" folder. list them as select options. once you select "use this folder" it then uses the current folder.

**Comment by tmbo** [comment]
fixed in #198
