### ISSUE TITLE
How to terminate app using ask() on keyboard interrupt?

### ISSUE THREAD

**Issue by bastienboutonnet** [tmbo/questionary#122]
When usinq the `Question.ask()` method, a keyboard interrupt is caught and replaced by a stout message. 

I am looking to cause my app to terminate on user interrupting. Not sure what would the best way to cause this behaviour given that the logger message isn't easily catcheable as an exception would.

Is there a neat way to do that? I can think of capturing the stout and generating my own exception but that feels annoying.

Alternatively, if you would b interested in allowing for the `.ask()` method to raise an error via an optional kwarg such as `raise_on_keyboard_interrupt` which would re-raise when `true` I'd be happy to get a PR up and running for this.

Let me know :)

**Comment by kiancross** [comment]
Hey :) You can call [`unsafe_ask`](https://questionary.readthedocs.io/en/stable/pages/advanced.html#unsafe), which does not catch the keyboard interrupt. Hope that helps.

**Comment by bastienboutonnet** [comment]
Oh yeah! I didn't look at the implementation of that method at all because unsafe made me think it would be a lot more unsafe than that but I just looked at the source code and yeah it seems `unsafe_ask()` is exactly what I was talking about helping to build into `ask()`.

Thanks a lot for the `prompt` reply --I know dad joke that I'm sure no one has ever made before...
