### ISSUE TITLE
Print select/rawselect as values with additional text?

### ISSUE THREAD

**Issue by mosfetish** [tmbo/questionary#123]
I have a dict with codes as keys and strings as value:

```
codes = {
    '123':  'Helper text for this code',
    '456':  'Helper text for this code,
    '789':  'Helper text for this code'
}
```

And I want this to appear in the select as:

123  Helper text for this code
456  Helper text for this code
789  Helper text for this code

So that when the choice is made for 456, only the value 456 is returned.

Is this possible? All I get from this now is the keys of the dict displayed as the list of choices.

**Comment by kiancross** [comment]
This should work:

```python3
import questionary

codes = {
    "123": "Helper text for this code",
    "456": "Helper text for this code",
    "789": "Helper text for this code",
}

x = questionary.select(
    "Select a code",
    choices=[
        questionary.Choice(title=f"{code} {text}", value=code)
        for code, text in codes.items()
    ],
).ask()

print(x)
```

**Comment by mosfetish** [comment]
Thanks. Worked. Closed.

The docs could be a bit clearer on the Choice Object, perhaps with more examples of how to populate it.
