### ISSUE TITLE
Allow arbitrary paths to be displayed in file path input

### ISSUE THREAD

**Issue by ewels** [tmbo/questionary#127]
I'm building an interface where the user is querying a remote file system. I love the File Path prompt and would like to use it, but here the files are not local.

It would be great if there was an option to provide an input with available file paths to use in the prompt.

**Comment by kiancross** [comment]
I think this can be done fairly easily by allowing a [custom completer](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html?highlight=completer#a-custom-completer) to be passed to the file path input:

https://github.com/tmbo/questionary/blob/2979fb8c6404f69112e8ebf918f9a2b29a310b45/questionary/prompts/path.py#L160-L162

The custom completer can return any path desired. This will probably also solve #120.

**Comment by tmbo** [comment]
fixed in #198

**Comment by ewels** [comment]
Awesome, thanks so much @tmbo! I'll give this a try ASAP.

Scanning over the new code quickly, it looks like there is a check that the provided directories exist - in my use case the file system is remote so this kind of check will fail. Is there a way to get around this? Apologies if I'm missing something obvious - just skim reading a PR on my phone at this point.

Thanks again,

Phil

**Comment by tmbo** [comment]
You still need to provide a custom completer, the one provided uses the file system to suggest the paths. But the PR (in addition to allowing to pass in a set of directories also allows to customize the completer, which is what you need).

The custom completer could look something like this (didn't test this code, just for inspiration):
```python
from typing import Iterable, List, Text
from prompt_toolkit.completion import CompleteEvent, Completer, Completion
from prompt_toolkit.document import Document

class RemotePathCompleter(Completer):
    """
    Complete for remote Path variables.

    You can use the completer by specifying it as part of a questionary path question:

    Example:
    ```
        paths = ["/a/foo", "/a/bar"]
        questionary.path("Path to the remote file", completer=RemotePathCompleter(paths)).ask()
    ```
    """

    def __init__(
        self,
        available_paths: List[Text],
    ) -> None:
        self.available_paths = available_paths

    def get_completions(
        self, document: Document, complete_event: CompleteEvent
    ) -> Iterable[Completion]:
        text = document.text_before_cursor

        for filename in self.available_paths:
            if filename.startswith(text):
                completion = filename[len(text) :]
                yield Completion(completion, 0, filename)

        
```

**Comment by ewels** [comment]
Amazing 🤩 Thanks so much for the explanation!
