### ISSUE TITLE
additional input for validation

### ISSUE THREAD

**Issue by 84matte84** [tmbo/questionary#167]
### Question

Hi all,

I was wondering how is it possible to pass additional values to the validation functions. 
As an example, how to modify the password_validator function given in the examples such that it becomes

  import re
  import questionary

  def password_validator(password, additional_input):
         .....

### What have you already tried?

I tried to play with **kwargs but with no success.

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
Can you give an example of what `additional_input` would be? What else is there to pass to the validator, other than the password?

**Comment by 84matte84** [comment]
It can be for example the length of the password or a list of character that can/cannot be used within the password but I don’t want to have a different validator for each of those possibilities.

Thanks

**Comment by kiancross** [comment]
You can use a lambda function to wrap around the call to `password_validator` and pass additional parameters.

E.g.

```python3
def validator(password, length):
    return len(password) >= length

questionary.password("Enter password", validate=lambda p: validator(p, 5)).ask()
```

**Comment by 84matte84** [comment]
it worked!! thanks a lot and sorry for the dumb question. :D

------ Original Message ------
From: "Kian Cross" ***@***.***>
To: "tmbo/questionary" ***@***.***>
Cc: "84matte84" ***@***.***>; "Author" 
***@***.***>
Sent: 9/10/2021 1:15:06 AM
Subject: Re: [tmbo/questionary] additional input for validation (#167)
