### ISSUE TITLE
autocomplete choice colors not readable

### ISSUE THREAD

**Issue by jvickroy** [tmbo/questionary#170]
### Question

**autocomplete** choices are rendered as light yellow text on a white background.  This is unreadable; how can the colors be reset?
Thanks,
/jim

### What have you already tried?

I do not know what to try.  Documentation for **autocomplete**  parameters does not appear to address this.

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by szemek** [comment]
@jvickroy you need to use `style` argument
https://questionary.readthedocs.io/en/stable/pages/types.html#autocomplete
Here you can find more details on themes & styling with examples https://questionary.readthedocs.io/en/stable/pages/advanced.html#themes-styling

**Comment by kiancross** [comment]
I'll close this issue as @szemek's answer should solve your problem :) Feel free to comment back on this issue if you need further help.
