### ISSUE TITLE
Add a confirm argument to password

### ISSUE THREAD

**Issue by johnthagen** [tmbo/questionary#174]
### Describe the problem

When prompting a user for a password, they cannot see what is input so it's more likely they could make a typo without realizing it. This is why most inputs that take passwords have the user type it twice, to avoid the situation where a single error slips through.

### Describe the solution

Add a new `confirm` `bool` argument to `password()`:

```py
def password(
    message: str,
    default: str = "",
    validate: Any = None,
    qmark: str = DEFAULT_QUESTION_PREFIX,
    style: Optional[Style] = None,
    confirm: bool = False
    **kwargs: Any,
) -> Question:
```

If `True`, `password` will prompt for a password and then display a `Confirm:` prompt. If the user enters the same text again, it returns, if not it loops until the user enters two identical strings.

**Comment by kiancross** [comment]
I think it is probably better to let the user implement this logic. It can be done fairly easily, as seen in this example:

```python3
import questionary

while True:
    x = questionary.password("Password").ask()
    y = questionary.password("Repeat password").ask()

    if x == y:
        print(x)
        break
    else:
        print("Passwords do not match. Try again.")
```

The user can then choose what to do in such an instance (e.g. keep retrying indefinitely, or retry 3 times etc).

What do you think?

**Comment by johnthagen** [comment]
@kiancross Yeah it's definitely valid to leave this up to the user.
