### ISSUE TITLE
Is this a bug, a feature, or just a bad use case?

### ISSUE THREAD

**Issue by amnuts** [tmbo/questionary#187]
### Question

Hi,

I'm trying to create a `checkbox` list that I'd like to contain a number of items that can't be turned off, but also still come back in the selected list when asked.  So I'm creating a `Choice` with `disabled` and `checked` both set to `True`, but the end result only contains values I have manually selected rather than _all_ those that are checked, even if they are disabled from allowing people to change them.

In my mind, if I'm setting the `checked` value on a checkbox, it should be included in the list even if it's disabled from the user being able to change the check state.

### What have you already tried?

Essentially I have something like:

````python
questionary.Choice(
    r["title"],
    value=r["value"],
    disabled=r["required"],
    checked=r["required"] or override_checked
)
````

where `r["required"]` is a boolean value, as is `override_checked`, but even with `True` for everything, this value would not be included.

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
I'm not sure if this is by design or not, but I agree it is probably not the expected behaviour. I think if a disabled option is selected, it should be both visibly selected and returned by the prompt. Feel free to submit a PR for this, otherwise I'll take a look in a couple of weeks :)

**Comment by amnuts** [comment]
Currently probably a bit beyond my knowledge of questionary to do a PR for this 😄

**Comment by kiancross** [comment]
No worries - I'll have a look in a couple of weeks :)
