### ISSUE TITLE
Default supplier

### ISSUE THREAD

**Issue by kadaan** [tmbo/questionary#189]
### Describe the problem

I would like to provide defaults based on prior answers.  For example, prompt for `<owner>` and `<service>`, then ask for `<service_name>` but have it default to `<owner>-<service>`.

### Describe the solution

Similar to how validation has been implemented, if I could provide a default supplier to a prompt, then I construct a rich default based on prior answers.  The function would have to accept a string of the configured value and the list of answers to date.  Then I would be able to implement the function using jinja2 to richly format a default value.

**Comment by kiancross** [comment]
I think what you are asking can already be done. Here is an example:

```python3
import questionary

owner = questionary.text("Owner:").ask()
service = questionary.text("Service:").ask()

service_name = questionary.text("Service name:", default=owner + "-" + service).ask()
```

Please let me know if I have misunderstood.

**Comment by kadaan** [comment]
@kiancross While that does work, it doesn't work if questionary is configured using a dictionary.  I would like to be able to configure questionary with a dict and provide functions for the defaults, validators, when, etc.  This allows the prompting to dynamically change based on the answers provided.

**Comment by kadaan** [comment]
Actually, I checked out the code again and see that default can be a callable, but it just isn't documented
