### ISSUE TITLE
Don't highlight default choice in Select questions

### ISSUE THREAD

**Issue by lyz-code** [tmbo/questionary#195]
### Question

I don't want to highlight the default choice in the `select` question.

### What have you already tried?

I've tried using my own styling, but I can't find the `class` that changes that behaviour. I've also checked the reference and the code to see if there was any option to disable this behaviour.

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
You can use the following style to remove the highlight:

```python3
questionary.Style([("selected", "noreverse")])
```

**Comment by lyz-code** [comment]
Works like a charm, thanks!
