### ISSUE TITLE
New question type: Autocomplete

### ISSUE THREAD

**Issue by joaquingx** [tmbo/questionary#20]
I would like to add a new question type, or maybe is an enhancement to `text` question type. Basically I want to add the option to autocomplete text, in my opinion it has a lot of advantages:
* For a list with more than 15+ items, `select` or another question type would be cumbersome.
* If the prompt is used continously for the same person, i think that this option would be his best option.
etc

I was learning about `prompt_toolkit` and seems quite possible(https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#autocompletion). What do you think @tmbo? If you think it is a good idea im ready to contribute :)

**Comment by tmbo** [comment]
Yes I think that would be a great addition 👍 could be an extension to text but if the code is different I’d rather go for a new type

**Comment by joaquingx** [comment]
Hi :smile: , this weekend i've been learning more about prompt_toolkit and questionary. In this research i found that questionary is not using the last version of  prompt_toolkit 2(2.0.10), and this might be an issue. Basically, in 2.0.7, autocompletion base class does not allow `formatted_text` in `display`. When I was exploring in prompt_toolkit, I found this example: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/auto-completion/colored-completions-with-formatted-text.py that i wanted to use as an inspiration to implement this feature. So, is possible to upgrade prompt_toolkit version?

**Comment by tmbo** [comment]
Sure, feel free to update :+1:

**Comment by tmbo** [comment]
implemented and merged ❤️  - will be part of 1.4.0 release
