### ISSUE TITLE
support Python 2.0

### ISSUE THREAD

**Issue by pyu10055** [tmbo/questionary#22]
We currently using PyInquirer, and we would like to switch to questionary, but we need python 2.0 support. In your opinion what needs to be done to support Python 2.0? We would be happy to contribute.
Thanks

**Comment by tmbo** [comment]
There wouldn't be large changes, but I imagine there are a couple of syntax things that are py3 specific. To be honest, I wouldn't want to maintain this project for py2 though, as lifetime of 2.7 is ending this year anyways.
