### ISSUE TITLE
Is there a way to turn the highlight for the choice selection?

### ISSUE THREAD

**Issue by iot-resister** [tmbo/questionary#229]
### Question

I'm trying to turn off the inverted colors every time the user make a checkbox choice. 

### What have you already tried?

I looked at the docs and promptool kit docs but I couldn't get anywhere. The following code just forces the colors black and white on select.  
```
        questionary.prompt(
            service_questions,
            style=questionary.Style(
                [
                    ("selected", "fg:white bg:black"),
                ]
            ),
            **kwargs,
        )
```

 I'd like to turn it off or just pass `("selected", "bg:transparent"),`

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
You can do something similar to https://github.com/tmbo/questionary/issues/195#issuecomment-999257280. E.g.

```python
questionary.checkbox(
    "Select toppings",
    choices=["foo", "bar", "bazz"],
    style=questionary.Style(
        [
            ("selected", "noreverse"),
        ]
    ),
).ask()
```

**Comment by iot-resister** [comment]
thanks!
