### ISSUE TITLE
Customize class:instruction on prompt creation

### ISSUE THREAD

**Issue by frankli0324** [tmbo/questionary#23]
Just another day when it comes to my mind "why not navigate with j and k in questionary.select" and it really worked, then I found #2 
The default hint text didn't mention that, so I looked into the library and found that `get_prompt_tokens()` literally returns "(Use arrow keys)".
A customizable text plz?

**Comment by tmbo** [comment]
Yes good point :+1: Would be great if you could provide a PR for that, happy to help out to improve this :rocket:
