### ISSUE TITLE
Allow searching `meta_information` in `autocomplete` question type

### ISSUE THREAD

**Issue by macintacos** [tmbo/questionary#239]
### Describe the problem

If you specify a dictionary of `meta_information`, the prompt that is provided is great. However, the text provided in the `meta_information` is not searchable - if I search for a word that is only in the `meta_information` dictionary, you'll be presented with no results.

### Describe the solution

I would like to be able to user the `autocomplete` action to search any text, regardless of whether it is in the `choices` or `meta_information`. The value chosen will still come from `choices`, but the searched text would be a merge of the two.	

### Alternatives considered

I tried merging the relevant information into the list of `choices` itself, but then when a user selects a choice I have to remove the extra information I added for searchability (because I only actually need a portion of the information in the choice). It's less than ideal.

If I'm missing some crucial piece of documentation, please let me know - I couldn't find anything in the documentation for this.

**Comment by kiancross** [comment]
You should be able to do this by passing a custom `completer` to the `autocomplete` prompt. You can see the implementation of the default completer here:

https://github.com/tmbo/questionary/blob/6643fe006f66802d9e504640f26b9e1a0a9d1253/questionary/prompts/autocomplete.py#L27-L100

You probably want to extend this and override the `_choice_matches` method to also search `meta_information`.
