### ISSUE TITLE
Questionary with pycharm line issues

### ISSUE THREAD

**Issue by WilliamStam** [tmbo/questionary#246]
### Question

anyone else seeing strangness with pycharm "run" and questionary? (its not a bug since its just pycharm strangeness)

using the demo code on pypi:
![image](https://user-images.githubusercontent.com/182800/184621396-0ae08e69-88fc-466e-b67d-948c968cf743.png)

windows 11
pycharm 2022.2
python 3.10
questionary 1.10

![image](https://user-images.githubusercontent.com/182800/184621584-777765b0-eff8-49d3-845c-8d64813933c3.png)
![image](https://user-images.githubusercontent.com/182800/184621685-3d54417a-b187-450b-a3e0-404ce52b7dfe.png)

### What have you already tried?

new test project. new venv. it all works fine when run in terminal / cmd / every where else. 
![image](https://user-images.githubusercontent.com/182800/184621975-936ca0d8-1081-4842-9ef7-45a5e9aa213b.png)

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
Is this still happening? It looks like there are various issues with `prompt_toolkit` (the underlying library) and PyCharm: prompt-toolkit/python-prompt-toolkit#782 prompt-toolkit/python-prompt-toolkit#825.

**Comment by WilliamStam** [comment]
on my side it seems to be resolved. im sorry i didnt close this. pycharm 2023.1 works fine. 

https://youtrack.jetbrains.com/issue/PY-57513/prompttoolkit-on-windows-on-2022.3-leads-to-prompttoolkit.output.win32.NoConsoleScreenBufferError-when-using-run

**Comment by kiancross** [comment]
No worries, thanks for updating!

**Comment by VaiaPatta1985** [comment]
It isn't fixed, it happened to me just now! Questionary version 2.1.1 and
```
PyCharm 2025.3.1.1
Build #PY-253.29346.308, built on January 9, 2026
Source revision: 692e552281d99
Runtime version: 21.0.9+1-b1163.86 amd64 (JCEF 137.0.17)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
  jetbrains.security.package-checker.enablePoetryTransitiveDependencies=false
  jetbrains.security.package-checker.enableUvTransitiveDependencies=false
  jetbrains.security.package-checker.depthLimitOfTransitiveDependencies=3
  jetbrains.security.package-checker.enableVenvTransitiveDependencies=false
  jetbrains.security.package-checker.enablePipEnvTransitiveDependencies=false
Non-Bundled Plugins:
  ru.adelf.idea.dotenv (253.29346.379)
  Batch Scripts Support (1.0.13)
  name.kropp.intellij.makefile (253.28294.218)
  Subversion (253.29346.379)
```
