### ISSUE TITLE
Test the questionary code

### ISSUE THREAD

**Issue by Rohan-cod** [tmbo/questionary#253]
### Question

Is there a way to test the questionary code if not native, via a third party?

### What have you already tried?

Read the docs but couldn't find a solution

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
Could you describe what exactly you are trying to do? If you're are asking about automated testing, there are some examples [here](https://github.com/tmbo/questionary/tree/master/tests) which may get you started.

**Comment by kiancross** [comment]
Closing this for now, but feel free to comment here if you have further questions.

**Comment by Alexander-Serov** [comment]
Just to complete the original question for future visitors: I understand the OP is referring to how to test an application (e.g. with `pytest`) using `questionary` inside. And at the first look, your link seems to provide an answer to it. For instance, [here](https://github.com/tmbo/questionary/blob/39f7d5f56b1a2fabedebcf5488b6f397333c1903/tests/test_form.py#L31).
