### ISSUE TITLE
Enable pointer and highlighted at the same time

### ISSUE THREAD

**Issue by Lee-W** [tmbo/questionary#26]
Hi, thanks for the great lib!

Currently, I'm working on things like the following.
![image](https://user-images.githubusercontent.com/5144808/68447844-5ebce900-021c-11ea-9bdf-7d9156558098.png)

However, in the current implementation, we cannot use pointer and highlighted text at the same time.
Maybe we can change the line here to enable it.
Or, is there any concern of it?
https://github.com/tmbo/questionary/blob/master/questionary/prompts/common.py#L229

**Comment by tmbo** [comment]
Yes that sounds good :rocket:

**Comment by layday** [comment]
It's not very obvious if a highlighted item is selected in checkbox layouts after this change.

**Comment by tmbo** [comment]
@layday do you have any suggestions on how to improve that?

**Comment by layday** [comment]
I suppose selected could be given higher precedence - if you were to simply swap the conditions around:

```diff
diff --git a/questionary/prompts/common.py b/questionary/prompts/common.py
index f652e62..3a2b843 100644
--- a/questionary/prompts/common.py
+++ b/questionary/prompts/common.py
@@ -278,14 +278,14 @@ class InquirerControl(FormattedTextControl):

                 if isinstance(choice.title, list):
                     tokens.extend(choice.title)
-                elif index == self.pointed_at:
-                    tokens.append(
-                        ("class:highlighted", "{}{}".format(shortcut, choice.title))
-                    )
                 elif selected:
                     tokens.append(
                         ("class:selected", "{}{}".format(shortcut, choice.title))
                     )
+                elif index == self.pointed_at:
+                    tokens.append(
+                        ("class:highlighted", "{}{}".format(shortcut, choice.title))
+                    )
                 else:
                     tokens.append(("class:text", "{}{}".format(shortcut, choice.title)))
```

I'm not sure if anything else makes use of `selected` though.

**Comment by tmbo** [comment]
@layday yes that sounds reasonable. do you mind creating a PR?
