### ISSUE TITLE
Page through larger lists of options with rawselect

### ISSUE THREAD

**Issue by tjirab** [tmbo/questionary#268]
### Question

`questionary.rawselect()` errors out when a list of choices exceeds 36.

```
ValueError: A list with shortcuts supports a maximum of 36 choices as this is the maximum number of keyboard shortcuts that are available. You provided 80 choices!
```

Couldn't find anything in the documentation regarding this use case. Does questionary offer the ability to page through choices? If not, do you have a recommendation to handle large lists?

### What have you already tried?

The below works, however if the desired choice is in the first batch you need to exit (CTRL+C) the next batches.
```python
options_int = list(range(0,80))
options = [str(o) for o in options_int]

if len(options) > 36:
    for i in range(0, len(options), 10):
        questionary.rawselect(
            "What do you want to do?",
            choices=options[i:i+10]
        ).ask()
```

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
There isn't currently a way to page a `rawselect`. The alternative is to just use a normal `select`, although with this you have to 'scroll' to select the option you want, rather than using shortcuts.
