### ISSUE TITLE
[ENH] Include `show_description` to `InquirerControl`

### ISSUE THREAD

**Issue by viniciusdc** [tmbo/questionary#269]
### Describe the problem

Well done on the project! I've been utilizing it extensively for dynamic CLI design.

Sometimes, CLI or workflow questions can be intricate, and supplying additional information regarding options can substantially enhance the user experience and effectiveness. I suggest integrating a `show_description` option into the `InquirerControl` class. This option would allow developers to include a brief description of the presently selected option, which would appear at the bottom of the current question, akin to the show_selected feature.

Integrating this option would enable users to rapidly comprehend each option's objective and make informed decisions, leading to a more user-friendly and efficient interface. This would aid in creating more insightful interactions within CLI or advanced workflows without any detrimental consequences.

For example, using the sample example from [select docs](https://questionary.readthedocs.io/en/stable/pages/types.html#select), we could have something as:
```python
import questionary

choice_options = [
      {
          "name": "Medium", 
          "value": "$15", 
          "description": "Available toppings: cheese, pepperoni, sausage"
       },
      {
          "name": "Big", 
          "value": "$20", 
          "description": "Available toppings: cheese, mushrooms, onions, peppers, pineapple, ham"
       },
]

question = select(
    "Select a pizza size: (see descriptions for toppings)",
    choices=choice_options,
    show_descriptions=True,
).ask()
```
![Peek 11-04-2023 14-33](https://user-images.githubusercontent.com/51954708/231243348-8fa4866e-6414-4c59-a49f-734c21109c41.gif)

### Describe the solution

- Extend Choices to receive the extra `description` attribute
- Extend `questionary.select` and `InquirerControl` to accept the new `show_description` flag

**Comment by viniciusdc** [comment]
I am willing to contribute with a PR if this addition looks reasonable.

**Comment by viniciusdc** [comment]
@kiancross I pinging you here cause I saw you were the latest one to merge a PR here. I would love for this to be included as well, and I can have a PR done too. Let me know what are your thoughts.

**Comment by kiancross** [comment]
Sorry for the slow reply. This looks reasonable, and a PR would be very much appreciated! Please make sure it is backwards compatible, and tests are included :)

**Comment by viniciusdc** [comment]
Hi @kiancross, thanks for having a look. We've created a PR with the suggested enhancements, and its ready for review :smile:
