### ISSUE TITLE
How to make text that is bold by default not bold?

### ISSUE THREAD

**Issue by CanePlayz** [tmbo/questionary#273]
### Question

I have a set of custom rules:

```py
custom_rules = [
    ("qmark", "fg:#1DB954"),
    ("question", "fg:#ffffff"),
    ("instruction", "fg:#1DB954"),
    ("pointer", "fg:#1DB954"),
    ("selected", "fg:#1DB954"),
    ("answer", "fg:#1DB954"),
]
```

The question and answer components are bold by default. When I define a new style for them (as above), they are still bold despite me not including bold in the style. How can I make those two components appear not bold?

### What have you already tried?

Nothing as I have no idea how to do that

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
You should be able to use `nobold` to remove the bold styling. More information on styling is available [here](https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/styling.html).

**Comment by CanePlayz** [comment]
> You should be able to use `nobold` to remove the bold styling. More information on styling is available [here](https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/styling.html).

Thanks
