### ISSUE TITLE
Checkbox make all choices preselected

### ISSUE THREAD

**Issue by pakiessling** [tmbo/questionary#284]
### Question

Thanks for the awesome library.

I would like to off the user multiple chechboxes, dynamically generated from a list, and they should all be selected by default. 

I am unsure on how to archieve this with the `Choice("foo", checked=True)` syntax, as the choices are not static.

Thanks for your help!

### What have you already tried?

This is the code I have so far:

```
questionary.checkbox(
            "Select Options:",
            choices=(machine_metadata["Options"])).ask(
)
```

`machine_metadata["Options"]` points to a list in a dictionary that may contain different values.

```
questionary.checkbox(
            "Select Options:",
            choices=(machine_metadata["Options"]),checked=True).ask(
)
```

does not work

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by RobertoPrevato** [comment]
Hi @pakiessling 
I just came across your question while taking a look at this library for the first time.

I think you should do instead:

```python
questionary.checkbox(
    "Select Options:",
    choices=[
        questionary.Choice(text, checked=True) for text in machine_metadata["Options"]
    ],
).ask()
```

(`checked=True` passed as a property of each instance of `Choice`, and not a property of the underlying `PromptSession`).

Working example:

```python
machine_metadata = {"Options": ["foo", "bar", "bazz"]}

questionary.checkbox(
    "Select Options:",
    choices=[
        questionary.Choice(text, checked=True) for text in machine_metadata["Options"]
    ],
).ask()
```

**Comment by pakiessling** [comment]
@RobertoPrevato Perfect, thank you so much
