### ISSUE TITLE
How to use rawselect without CPR?

### ISSUE THREAD

**Issue by halloleo** [tmbo/questionary#29]
I love questionary! It is certainly the right way forward in the command line dialogs space.

I tried out the `rawselect.py` example and have problems on simple terminals (TERM=dumb or TERM=unkown) which do not cater for CPRs (cursor position requests). In this case `questionary` prints out

    WARNING: your terminal doesn't support cursor position requests (CPR).

The warning comes from `prompt_toolkit` I suspect, but is there a way to tell `questionary` to simplify the prompting so that no CPRs are required? After all the user just will type a number to select an option!

**Comment by halloleo** [comment]
I found a way to "better" the situation: Before calling `questionary.rawselect` set

        os.environ['PROMPT_TOOLKIT_NO_CPR'] = '1'

and at least the warning disappears. However there is still a problem when running `rawselect` in a dumb terminal :

The `message` string you provide to the function is nowhere displayed while the (numbered) choices are shown.

**Comment by tmbo** [comment]
Mhm, is there any way to reproduce this on OSX?

I mean we can check if `CPR` is possible on the renderer of prompt_toolkit, but I am not sure that works before the prompt is actually run. 

In any case, maybe you can create a PR - I am happy to merge it given there is some way to reproduce this

**Comment by halloleo** [comment]
Yes, easy to reproduce on macOS: Just run one of your samples in a shell buffer in Emacs (that is a rather dumb terminal). I can give you the steps for how to do this,if that helps.

**Comment by halloleo** [comment]
Good news @tmbo! prompt-toolkit has now a basic way to handle dumb terminals! :-) Thanks to @jonathanslenders [this is added to master](https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1035)  (and will make its way into the pip package, I guess) but as prompt_toolkit **3.0**. The problem is you pin prompt_toolkit as version '~=2.0'.

**Comment by halloleo** [comment]
I just saw there is an issue (#31) dealing with using V3 of prompt-toolkit. So after that issue is resolved we might be able to close this here automatically. :)

**Comment by tmbo** [comment]
That's great news, I am currently looking into getting it to work with prompt toolkit V3 and it is looking good. there are only some autocomplete tests which are failing for unknown reasons.

**Comment by tmbo** [comment]
I've just released questionary version 1.5 which supports prompt_toolkit 3

Do you mind checking if it works with the dumb terminal?

**Comment by kiancross** [comment]
@halloleo Is this working on dumb terminals now?

**Comment by halloleo** [comment]
Thanks. Will check it out in today or tomorrow.

**Comment by halloleo** [comment]
Hey, it works well now using questionary 1.5.2 and ptk 3.0.7. Thanks!
