### ISSUE TITLE
Apply multiple validators to question

### ISSUE THREAD

**Issue by marcosdotme** [tmbo/questionary#297]
### Question

There's an way to apply multiple validators to an question?

```python
def ask_dictstyle(**kwargs):
    questions = [
        {
            "type": "text",
            "name": "phrase",
            "message": "Type an phrase?",
            "validate": [
                lambda p: len(p) >0,
                lambda p:  "questionary" in p
            ]
        }
    ]
```

### What have you already tried?

I have this two validators:

```python
def required_answer_validator(answer_title):
    def has_answer(answer):
        if not answer:
            return f"'{answer_title}' is required."

        return True

    return has_answer


def nsfw_validator(message):
    def has_nsfw(answer):
        if 'nsfw' in answer:
            return message

        return True

    return has_nsfw
```

And I need to apply this two validators on an single question, without needing to "concatenate" this two functions manually.

I tried things like that, what is intuitive but don't works:
```python3
{
    "type": "input",
    "name": "issue_title",
    "message": "Issue title:\n ",
    "validate": [
        required_answer_validator(answer_title='Issue title'),
        nsfw_validator(message='NSFW detected')
    ],
    "qmark": "\n*"
},
```

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
There is no way to do this natively. You should concatenate the error messages yourself with a wrapper function.

**Comment by marcosdotme** [comment]
@kiancross I created one wrapper functions as you mentioned. The syntax is:

```python
{
    'type': 'input',
    'name': 'issue_number',
    'message': 'Issue number:\n ',
    'validate': apply_multiple_validators(
        validators=[
            required_answer_validator,
            is_equal_to_1,
            is_equal_to_word(word='questionary')
        ],
    ),
    'qmark': '\n*'
},
```
Validators that receives arguments need to be writed as:
```python
def is_equal_to_word(word):
    def _is_equal_to_word(answer):
        if str(answer) == str(word):
            return f"Cannot be {word}"
    
        return True
    
    return _is_equal_to_word
```

Do you think it's relevant to open a PR?

**Comment by kiancross** [comment]
> Do you think it's relevant to open a PR?

Imo, it's generally better to only extend the API if doing so is necessary to achieve something which can't be done otherwise. So I don't think there is a need for a PR in this case.
