### ISSUE TITLE
Using YAML files instead of a python dictionary?

### ISSUE THREAD

**Issue by sshakoor1** [tmbo/questionary#298]
### Question

Currently I am using the prompt() function on a dictionary created from a YAML file. This, however, comes with some limitations. For example, any mapping that requires a function will not be interpreted as python code, but as a string. I can get around this by using eval().

test.py:
```
import questionary
import yaml
from questionary import prompt

def getFirstWord(input):
        return value.split(None, 1)[0]
        
with open('test.yaml', 'r') as file:
        questions = yaml.safe_load(file)

for key, val in questions.items():
    for i, d in enumerate(val):
        # if "<filter>:" is seen, evaluate its mapping as python code
        if 'filter' in d.keys():
            questions[key][i]['filter'] = eval(d['filter'])        

answers = prompt(questions['questions'])
```
test.yaml:
```
questions:
  - name:     'favFood'
    type:     'select'
    message:  'Select one:'
    choices:  ['pizza is my favorite food', 'sushi is my favorite', 'tacos are my favorite food']
    filter:   getFirstWord
```

The problem here is, well, I'm using eval() which is generally a terrible idea. My question is: is there another way to replicate this with without eval()? Or is this just a dumb idea to begin with, and should avoid using prompt() with a YAML file? 

### What have you already tried?

see above.

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by kiancross** [comment]
You can use `eval` if you know the input you are being provided with is safe. However, if you are trying to make your code more modular, you would be better off using separate Python files rather than Yaml files.

Why do you want to use Yaml files?

**Comment by sshakoor1** [comment]
Well, because my boss asked for it to be that way. I agree though I think using separate python files would be better, I'll talk to him about it.

**Comment by kiancross** [comment]
I'll close this issue, but feel free to post back if you have additional questions.
