### ISSUE TITLE
Possible CPR (cursor position requests) issue

### ISSUE THREAD

**Issue by mart1n** [tmbo/questionary#3]
First off, I'm not sure if this is a bug/issue in this project or not.

Whenever I use the select, rawselect or checkbox question types, the list of selections is displayed half-a-screen down from the question text.

I used PDB to step through the code and it didn't reproduce the issue, but instead I got the log message, "WARNING: your terminal doesn't support cursor position requests (CPR)". The log message comes from prompt_toolkit.application.application (line 724). From briefly looking through that code, I noticed that it wasn't reproducing the issue because the CPR request timed out, due to how long it took me to step through the code. If I run the same test through PDB, but quickly step, it reproduces.

Do you have any experience with this type of issue? Or have any idea why the cursor position request would return a position so far down from where the question text is being displayed?

I tested in xterm/bash and a regular virtual terminal/bash on the following platform.
Linux mjk 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

Thanks!

**Comment by tmbo** [comment]
I have seen this happen as well a couple times. I couldn't reproduce it consistently though - I'll do some digging to check if there is an underlying issue in the prompt_toolkit or if it stems from the way it is used in the project.

**Comment by mart1n** [comment]
I'm available for additional testing, if you have any requests. It consistently reproduces on my system.

**Comment by tmbo** [comment]
@mart1n I think I found the issue and I've pushed a fix to master - do you mind trying it out?

**Comment by tmbo** [comment]
Awesome, I'll create a release then. 

The main change is this line https://github.com/tmbo/questionary/commit/00751fae7888367fb66905a575ac771ad2e5cc22#diff-0eccf09aa36dc0dd59d841a342a6b76bR286 - it makes sure the "window" which contains the question does not use unused space. Instead, it selects the max height in a way that all the content is visible (in our case the question) but no new lines.

**Comment by tmbo** [comment]
I've released an updated version `1.0.1` that includes the fix.
