### ISSUE TITLE
prompt-toolkit v3 compatibility

### ISSUE THREAD

**Issue by layday** [tmbo/questionary#31]
The autocomplete tests are failing with `prompt-toolkit==3.0.2`, ostensibly because it's not registering any of the tab escapes.  I did some bisecting and [this](https://github.com/prompt-toolkit/python-prompt-toolkit/commit/c7851c09ffbfa7d06458408abee77ab6f548852d) absolutely massive (!) commit is the one that broke it.  If you'd like to get support for v3 in, I can try digging a bit deeper.

**Comment by tmbo** [comment]
@layday yes I'd love to get this in - would be great if you can take a closer look :rocket:

**Comment by layday** [comment]
So, on the v3 branch, the completions aren't generated until the entire key sequence is read in.  A tab event _is_ triggered but the completions aren't there for the test to tab through.  I'm guessing it's got something to do with the new async tooling - something might be blocking to completer - but the codebase is really opaque to the uninitiated (that's me).
