### ISSUE TITLE
Publish documentation of 2.0.0

### ISSUE THREAD

**Issue by ralbertazzi** [tmbo/questionary#317]
### Describe the bug

The changelog of 2.0.0 is not present on [readthedocs](https://questionary.readthedocs.io/en/stable/pages/changelog.html). I was only able to find the changelog in [here](https://github.com/tmbo/questionary/pull/300/files)

### Example

```python
-
```

### Expected behaviour

The documentation of `questionary` 2.0.0 live on readthedocs

### Latest version

- [X] I have checked that this issue occurs on the latest version of questionary.

### Questionary version

-

### Prompt Toolkit version

-

### Operating System

Other (please specify in description)

**Comment by kiancross** [comment]
It looks like the documentation has been broken for a couple of months. I'll investigate. Thanks for reporting this!

**Comment by kiancross** [comment]
https://questionary.readthedocs.io/en/latest/ now contains the fixed documentation. Currently working on getting `stable` fixed, too.
