### ISSUE TITLE
Update prompt_toolkit to be compatible with ipython

### ISSUE THREAD

**Issue by FantasqueX** [tmbo/questionary#344]
### Question

Hi, thanks for this wonderful library. My issue when using questionary is that the latest questionary requires prompt_toolkit<=3.0.36    https://github.com/tmbo/questionary/blob/master/pyproject.toml#L36 while another popular tool ipython requires prompt_toolkit>=3.0.41 https://github.com/ipython/ipython/blob/main/setup.cfg#L38. Because of pip's terrible dependency management, I cannot make questionary and ipython be both happy.

I saw you referred to an issue https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1726, however it's not convenient to reproduce with a not well-maintained library(jellex). I wonder whether you can check 3.0.42 prompt_toolkit is compatible with questionary or provide a small reproducible code with questionary. Thank you.

### What have you already tried?

Took a look at https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1726

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by gsakkis** [comment]
I also ran into this with ipython.
> Because of pip's terrible dependency management, I cannot make questionary and ipython be both happy.

What terrible dependency management? There are two packages with conflicting requirements, what is pip (or any other dependency manager) supposed to do other than error out mentioning the conflict?

**Comment by kiancross** [comment]
I've marked this as an enhancement. Happy to review any PRs for this.

**Comment by Em1lyK** [comment]
I'm facing this issue as well

**Comment by tosilswc** [comment]
PLEASE merge FantasqueX fork into the official repository, the dependency issue is fixed by substituting the official package with the fork.

**Comment by danieltomasz** [comment]
This might be related https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1809

**Comment by CyberTailor** [comment]
Can you make a bugfix release? v2.0.1 can't be packaged in distro repos as-is because of this problem.

If not, packaging v2.0.1 with https://github.com/tmbo/questionary/commit/9bb5ae1d740ec8d6b3caf3d81a9f71dc13bdd135 patch applied will do the thing.

**Comment by kiancross** [comment]
@CyberTailor A new release will be available in the next couple of days. PR #416. Apologies for the delay.
