### ISSUE TITLE
Allow "confirmatory" enter to confirm dialog

### ISSUE THREAD

**Issue by xmatthias** [tmbo/questionary#37]
When using the prompt-type confirm - it's really odd to me that pressing Y / n will immediately confirm the action and move forward. 

I think the current approach of auto-confirm will work fine for single, confirmatory questions - but can be a problem for workflows.

For that, i'd propose to have an option like "autoenter" - which should default to true (to keep existing behaviour) - however it'll allow myself to have the user press Y  / n - think about it - and then press enter explicitly.

The way current way is a problem as i find myself pressing "y" - "Enter" (obviously out of habit).

Since I'm building a workflow of multiple consecutive actions (all with defaults), i find myself constantly skipping / confirming the question right after the Confirm question - and i suspect that our users will face the same issue - if they're used to bash-like cli interfaces, which usually require a "n\r" - not just a "n".

Hope this makes sense

**Comment by WilliamStam** [comment]
im also finding this to be a bit out of place. agree with the suggestion
