### ISSUE TITLE
Is there a way to modify defaults, or at least inherit them from previous Question?

### ISSUE THREAD

**Issue by raimondi1337** [tmbo/questionary#370]
### Question

I've been looking through the docs but I can't find anything about this.

Say I want to set `qmark` to ` - ` all the time, or have every `select` default to `use_shortcuts=True`.
Can I just override the defaults one time somehow, rather than putting the args in every prompt in every prompt?

It does not seem like I have access to `constants.py` or a way to override the function definitions.

### What have you already tried?

Reading the docs, looking through package code

### Read the documentation

- [X] I have checked to ensure that my question is not answered by the documentation.

**Comment by tmbo** [comment]
You could create a partially aplied function and use that, e.g.

```
import questionary 
import functools

select_with_shortcut = functools.partial(questionary.select, use_shortcuts = True)
```

or create a wrapper function

```
import questionary

def select_with_shortcut(*args, **kwargs):
  if not "use_shortcuts" in kwargs:
    kwargs["use_shortcuts"] = True
  return questionary.select(*args, **kwargs)
```
