### ISSUE TITLE
Allow more convinient selection

### ISSUE THREAD

**Issue by blackliner** [tmbo/questionary#393]
### Describe the problem

I'm always frustrated when I need to select a choice on the bottom of the list, because I press `[PageDown]` and it has no effect. I also try to press `/` (like in vi) and start typing for the selected item, which also does not work. Just typing also has no effect. It looks like the only supported input us `[ArrowUp]`, `[ArrowDown]`, and `[Return]`

### Describe the solution

I would like to just start typing and either get pointed directly to the closest match, or everything else is filtered out fuzy style. Or Other means to navigate the list quickly, like `[PageDown]`, `[Home]`, `[End]` etc.

**Comment by kiancross** [comment]
Hi @blackliner. Searching has just been added in #374.

**Comment by kiancross** [comment]
@alexverdes I am working on a new version now :)
