### ISSUE TITLE
feat: add search functionality to select and checkbox 

### ISSUE THREAD

**Issue by nvpnathan** [tmbo/questionary#400]
### Describe the problem

Is it possible to create another release that supports the search functionality for select and checkboxes?

### Describe the solution

I believe the code is in the repo but no new release has been pushed to support the functionality.

**Comment by RafikLkr** [comment]
I would like to work on this issue. Could you assign it to me please ? Thank you :)

**Comment by nvpnathan** [comment]
@tmbo any consideration in pushing a new version tag up to pypi? Love the search feature for lists. It would be awesome to have this installed via requirements.txt or pip. Any guidance here would be appreciated.

**Comment by kiancross** [comment]
@nvpnathan A new release will be available in the next couple of days. PR #416. Apologies for the delay.
