### ISSUE TITLE
'prompt_toolkit' version dependency update needed to 3.0.48 for radian package compatibility

### ISSUE THREAD

**Issue by jwoolfolk** [tmbo/questionary#404]
### Describe the bug

Upon installing questionary, I lose functionality in my terminal to my radian package for r development due to conflicting dependencies on differing versions of prompt_toolkit.  Can this requirement be updated to allow for prompt_toolkit version 3.0.48 be used?

Error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
questionary 2.0.1 requires prompt_toolkit<=3.0.36,>=2.0, but you have prompt-toolkit 3.0.48 which is incompatible.

Upon running 'pip install --upgrade questionary':

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.28.0 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
radian 0.6.13 requires prompt-toolkit<3.1,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.

### Example

```python
pip install radian
pip install questionary
pip install --upgrade radian
pip install --upgrade questionary
```

### Steps to reproduce

1. Install radian package via cmd prompt
2. Install questionary package via cmd prompt
3. Load VSCode Terminal
4. Error within integrated terminal regarding radian package.
5. Return to cmd prompt and 'pip install --upgrade radian'
6. ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
questionary 2.0.1 requires prompt_toolkit<=3.0.36,>=2.0, but you have prompt-toolkit 3.0.48 which is incompatible.
7. Return to cmd prompt and 'pip install --upgrade questionary'
8. ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.28.0 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
radian 0.6.13 requires prompt-toolkit<3.1,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.

### Expected behaviour

No error seen in regards to using either package.

### Latest version

- [X] I have checked that this issue occurs on the latest version of questionary.

### Questionary version

2.0.1

### Prompt Toolkit version

3.0.48

### Operating System

Windows

**Comment by sshishov** [comment]
Same issue here. Is this strict pin needed for `prompt_toolkit`?

**Comment by etsvetanov** [comment]
Can we do something to help fix this issue?

**Comment by riziles** [comment]
This issue was resolved a while ago: https://github.com/tmbo/questionary/pull/347 , but the maintainer has not created a new release. Somebody should fork this project. It's causing downstream issues for lots of people.

**Comment by kiancross** [comment]
A new release will be available in the next couple of days. PR #416. Apologies for the delay.
