### ISSUE TITLE
Add Option Limit for Checkbox Selection 

### ISSUE THREAD

**Issue by kotazzz** [tmbo/questionary#407]
### Describe the problem

I'm always frustrated when I need to limit the number of options a user can select in a Checkbox prompt in questionary. Currently, there's no built-in way to restrict how many options can be selected, which requires manual checks after the user submits their choices.

### Describe the solution

I would like questionary to support an option that limits the number of selections a user can make in a checkbox list. This can be done by adding a new argument (e.g., max_selection) to the Checkbox prompt, which will ensure the user can only select up to a defined number of options. If the user exceeds the limit, an error or a message should be displayed to prompt them to reduce their selection.

### Alternatives considered

As an alternative, I considered manually validating the number of selections after the user makes their choice, but this adds unnecessary complexity and doesn’t provide a smooth user experience. Having built-in functionality would simplify the process and improve usability.

**Comment by amnuts** [comment]
I know this isn't a dedicated property for it, @kotazzz, but have you tried using the `validate` property for the checkbox, rather than doing it after the fact?  Something like, perhaps:

```
checkbox(
    "Select this things...",
    choices=thing_to_select,
    use_arrow_keys=True,
    validate=lambda selected: (
        True
        if len(selected) <= 5
        else "You can only select up to five things"
    ),
)
```

**Comment by kotazzz** [comment]
@amnuts to be honest, I completely forgot about the existence of validate and the code looks quite convenient. I think this is the best way to do what I want

**Comment by kiancross** [comment]
I'll close this given you have found an acceptable alternative, but if you think this still has its use cases, let me know, and I will reopen.
