### ISSUE TITLE
Programmatically define pointed-at option for select

### ISSUE THREAD

**Issue by beeb** [tmbo/questionary#43]
Let me preface this by saying that I love questionary and I'm thankful to you guys for making it :)

I would like to suggest adding a feature to the `select` prompt. Currently, I think (by looking at the code) that there is no way to change which item in the select is pointed at (has the pointer symbol) when it gets initialized. It's always the first selectable choice that gets pointed at.

I would like to be able to start the `select` in a state where the pointer is on another choice (for instance the first one that has a value matching the `default` argument of the `select` call).
Another option would be to have an additional argument for `Choice` objects where we can say we want it to be pointed at initially.

Passing the `default` argument highlights the Choice that corresponds, but the pointer is still in the first position.

Thanks!

**Comment by tmbo** [comment]
@beeb I think that is a great idea - selecting the default on startup should be a reasonably easy thing to do :+1:
