### ISSUE TITLE
Color of answer for text prompt doesn't change

### ISSUE THREAD

**Issue by falkyre** [tmbo/questionary#45]
I've just switched over from PyInquirer to questionary and it was a seamless transition.  Kudos to you for creating questionary.  One thing I noticed under PyInquirer and a text prompt is that when I get the answer, the answer is high lighted in a different color.  Under questionary, that color doesn't change.  Am I missing something?  I would think that the answer should be able to be styled as the other prompts but I can't get it working no matter what I do.

Thanks.

**Comment by falkyre** [comment]
One of left is Questionary and one on right is PyInquirer.  The line **When do you want the end of the day to be?**. I'd like the answer to be the same color as the question above it
![Screen Shot 2020-03-11 at 3 32 03 PM](https://user-images.githubusercontent.com/7012886/76461265-9647c780-63ad-11ea-9194-4cf4a0cfa305.png)

**Comment by nmstoker** [comment]
This also happens with the results from an "autocomplete" question.  Think it's the same cause (not applying the answer style to the final response, although in the autocomplete I also think styling is slightly off in general, as answer _is_ used to style the drop-down, which is not the way I think most people would expect)

**Comment by kiancross** [comment]
Here is an example:
```python3
import questionary

questionary.select(
    "Select an option",
    choices = ["foo", "bar"]
).ask()

questionary.text("Write some text").ask()
```
