### ISSUE TITLE
Documentation request: documentation for all different question choices

### ISSUE THREAD

**Issue by Zylvian** [tmbo/questionary#47]
Had to dive through some examples to find stuff like 'when' and 'validate'. Would be nice with a sheet of available keys for each question.

**Comment by kiancross** [comment]
@tmbo What do you think about creating a [Read the Docs](https://readthedocs.org/) style of documentation for this?

**Comment by tmbo** [comment]
@kiancross yes I think that is a great idea. I think we got to a point where, even though need, the readme documentation is growing beyond being easy to navigate :+1:

**Comment by kiancross** [comment]
@tmbo Ok I will have a look at this in a few weeks when I have some more time :)

**Comment by kiancross** [comment]
@tmbo Do you have any preference over using Read The Docs vs GitHub pages to host the documentation?

**Comment by tmbo** [comment]
mhm no not really, I think either one is fine 👍
