### ISSUE TITLE
How to write tests for applications that use questionary?

### ISSUE THREAD

**Issue by Zethson** [tmbo/questionary#49]
Dear @tmbo ,

I am trying to test an python application of mine which uses questionary.
However, I am lost when trying to test the application.

from click.testing import CliRunner
runner = CliRunner()
`result = runner.invoke(myapplicationfunction, input='\n')`

The code above should call myapplicationfunction which opens questionary prompts and then simply enter once, which is equivalent to \n. 
The same thing works when running echo -e "\n" | python filewhichcallsmyapplicationfunction.py 

However, when running it via the runner it does not work. Reason being: it just passes stdin.

The error message is:

```
E               io.UnsupportedOperation: Stdin is not a terminal.

bla/site-packages/prompt_toolkit/input/vt100.py:57: UnsupportedOperation
```

How do I test such scripts, which simply open questionary prompts?
Do you have a pytest example?

**Comment by kiancross** [comment]
Have a look at how the questionary unit tests work, for example: https://github.com/tmbo/questionary/blob/153f30252812409b21e9243150ce39b4ef72e806/tests/prompts/test_text.py#L17

Specifically, the following function may be helpful in your implementation: https://github.com/tmbo/questionary/blob/153f30252812409b21e9243150ce39b4ef72e806/tests/utils.py#L25

**Comment by Zethson** [comment]
@kiancross Thanks, will take a look and close this issue if I succeed!

**Comment by Zethson** [comment]
We are currently still struggling. We don't have the case where the input can be directly fed into the questionary functions, since between questionary calls there may still be stuff going on and the input cannot be used as easily one after another.

An example:

```
import questionary


def cookietemple_questionary(function: str, question: str, choices: list = None, default: str = None) -> Union[str, bool]:
    answer = ''
    if function == 'select':
        answer = getattr(questionary, function)(f'{question}: ', choices=choices).unsafe_ask()
    elif function == 'text':
        answer = getattr(questionary, function)(f'{question} [{default}]: ').unsafe_ask()

    return answer


def testme(bar):
    baz = cookietemple_questionary('select', 'Select a pizza topping', ['pineapple', 'sausage'], 'sausage')

    baz = f'{baz} is my favorite topping'

    do_something(baz)

def do_something(baz):
    foo = cookietemple_questionary('text', 'How old are you', '14')

    real_age = 10 + int(foo)

    return real_age
```

Ideally we would like to test testme with a single string, that already has all the answers to all questionary prompts.
e.g. our string would look like:
```
input_pipeline = f'{KEYBOARD.DOWN}{KEYBOARD.ENTER}25'
```
The first question would take the first answer and the second question then takes the second answers. This is also how we are testing for example with Click.

If we were unclear with our explanations please tell us and we will get back to you as soon as we can.  

Cheers

**Comment by kiancross** [comment]
@Zethson I'm not entirely sure what you're asking/what your use case is.

You can copy the `feed_cli_with_input` (and all the imports) and use it in your test suite. I have one example using a text prompt, but you can look at how to test all inputs in the `tests` directory.

You can take the output from `feed_cli_with_input` and use it to generate the input for your next test how you wish.

**Comment by Zethson** [comment]
No, we can't simply take the method and use it for our use case. Of course we also had that idea :)

```
import questionary


def cookietemple_questionary(function: str, question: str, choices: list = None, default: str = None) -> Union[str, bool]:
    answer = ''
    if function == 'select':
        answer = getattr(questionary, function)(f'{question}: ', choices=choices).unsafe_ask()
    elif function == 'text':
        answer = getattr(questionary, function)(f'{question} [{default}]: ').unsafe_ask()

    return answer


def testme(bar):
    baz = cookietemple_questionary('select', 'Select a pizza topping', ['pineapple', 'sausage'], 'sausage')

    baz = f'{baz} is my favorite topping'

    do_something(baz)

def do_something(baz):
    foo = cookietemple_questionary('text', 'How old are you', '14')

    real_age = 10 + int(foo)

    return real_age
```

Again, what would a test look like for the function **testme**?
You can't just use the `feed_cli_with_input` method to solve this (in our opinion).

Sorry for bothering you with this, but our use case is more complex and we don't know how we should proceed here.

**Comment by kiancross** [comment]
@Zethson Is there a reason you're not unit testing? This would be very easy if you were doing unit tests, but it sounds like you're trying to test your whole programme at once?

You could simply do `printf "\r50\r" | python3 example.py` to pipe some input into your example. You could then redirect the output of the programme to a file and compare that with the expected result.

If you want a pure Python example, have a search for a way to invoke a function with a different `stdin` - you can probably do it by creating a new thread or process.

**Comment by Zethson** [comment]
Yes, there is a reason for this.
We have nested functions which at different points of time in between pieces of code have questionary prompts.
Those functions have dependencies on each other, which cannot be mocked nor unit tested, since we require a final result.

We replaced click with questionary. Back when we were using Click, we did exactly what you recommended. We passed our main entry point something like `echo -e foo\nbar\n | entrypoint`. 
But since we switched to questionary we can no longer do that.

This was mentioned in the first post above:

"
```
from click.testing import CliRunner
runner = CliRunner()
result = runner.invoke(myapplicationfunction, input='\n')
```

The code above should call myapplicationfunction which opens questionary prompts and then simply enter once, which is equivalent to \n. 
The same thing works when running echo -e "\n" | python filewhichcallsmyapplicationfunction.py 

However, when running it via the runner it does not work. Reason being: it just passes stdin.

The error message is:

```
E               io.UnsupportedOperation: Stdin is not a terminal.

bla/site-packages/prompt_toolkit/input/vt100.py:57: UnsupportedOperation
```
"

**Comment by kiancross** [comment]
@Zethson Well here is a super hacky way you could do it. Essentally just recreating what the pipe symbol (`|`) does in Bash, but in Python instead:

```python3
import sys 
import os

# Put your test code here

input_str = b"\r50\r"

r, w = os.pipe()
os.dup2(r, sys.stdin.fileno())
os.write(w, input_str)

testme(None) # Call your test function with new stdin.
```

**Comment by kiancross** [comment]
@Imipenem Glad it works. You could ask @Zethson To close this issue if it is all sorted?

**Comment by Zethson** [comment]
Yes, we're a team  
Thanks! 👍
