### ISSUE TITLE
Multiline input

### ISSUE THREAD

**Issue by Yajo** [tmbo/questionary#54]
I'd need an option to have multiline input.

Something similar to https://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#multiline-input

Is that possible or planned?

**Comment by Yajo** [comment]
It seems that calling `questionary.text("tell me something", mulitline=True)` just works. What's missing:

- Help text that indicates the user to end with `Alt+Enter` or `Esc, Enter`.
- Docs.

**Comment by kiancross** [comment]
@Yajo Nice find. I'm going to try and add some better documentation (#47). Feel free to send a PR in with help text, or I'll look at it when I get a chance.

**Comment by Yajo** [comment]
See #59 :gift:
