### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by tmbo** [tmbo/questionary#62]
@kiancross do you want to do the honours of releasing 1.6.0? https://github.com/tmbo/questionary#developer-info

**Comment by kiancross** [comment]
@tmbo Directly to the repo, or via a pull request?

**Comment by tmbo** [comment]
feel free to do it on master :+1:

**Comment by harens** [comment]
Hi there. Just to let you know that as of https://github.com/macports/macports-ports/pull/8634, on cue with your release, I've updated the portfile for questionary. You can find a summary page [here](https://ports.macports.org/port/py-questionary/summary).

I don't think I mentioned that I added your project to MacPorts when I wrote the portfile (sorry about that), but from `v1.5.2`, your project could be installed by running the following on macOS:

```
sudo port install py-questionary
```

Similar to this release, I'll try to keep updating the portfile for as long as I can. I'm more than happy to answer any questions if you have any. Thanks 😁.
