### ISSUE TITLE
Type hinting not working

### ISSUE THREAD

**Issue by davnat** [tmbo/questionary#75]
Hi, thanks for this library, it's very nice.

In my project `mypy` keeps complaining:

```python
import questionary

questionary.select(etc..)
```
```
$ poetry run mypy -p mypackage
error: Module has no attribute "select"
```
I've only been able to have `mypy` working by adding the `__all__` attribute to `questionary/__init__.py`, with all the needed exports.

Maybe I am missing something?

Thank you, cheers

**Comment by layday** [comment]
Mypy expect symbols to be re-expected (i.e. `from questionary.prompts.select import select as select`) in strict mode, even for non-stub files. `__all__` has the same effect, as you've observed.

**Comment by davnat** [comment]
Are you suggesting that I should re-export questionary symbols?

In any case, something like `from questionary.prompts.select import select as select` makes both flake8 and pylint complain (unused import, useless import alias), while `__all__` makes everyone happy, because it makes clear what's the purpose of the import.

**Comment by layday** [comment]
No, I mean that they need to be re-exported in Questionary's `__init__.py`.

**Comment by layday** [comment]
I pushed two commits to #68 which address this and your other issue should it be merged.
