### ISSUE TITLE
Synchronous questionary calls in an async function

### ISSUE THREAD

**Issue by davnat** [tmbo/questionary#83]
Hello,
Is there a way to run synchronous questionary calls in an async function?
I need to make something like this work:
```python
import asyncio
import questionary

async def main() -> None:
    questionary.select(
        "What do you want to do?",
        choices=[
            "Order a pizza",
            "Make a reservation",
            "Ask for opening hours",
        ],
    ).ask()

asyncio.run(main())
```
In my application I'm not calling questionary directly (the test above is an oversimplified example): I need to support different toolkits, so I created a wrapper around questionary.
I know questionary has an async API, but I'd need to expose it in the wrapper and add `await` to every call, without any real need for an async API: only to make it work.

Thank you, cheers

**Comment by tmbo** [comment]
I am not quite sure I fully understand your example, using await should do what you need, shouldn't it:
```
async def wrapper():
    await questionary.text("Test").ask()
```

**Comment by davnat** [comment]
In my use case I don't need to do asynchronous questionary calls.
Nevertheless, I'm using both sync and async functions in my code (in different projects using the wrapper).

The problem is: inside an async function I am forced to use the questionary async API, while in theory a synchronous call should be perfectly legal, AFAIK.

This forces me to provide 2 nearly identical wrappers, one sync and one async, while the sync wrapper should be enough.

**Comment by tmbo** [comment]
you can create wrappers which work async and sync, e.g. this is a decorator that can be used for `async def` and `def` functions:
```python
from functools import wraps
from typing import Any, Callable
import asyncio

def universal_decorator(f: Callable[..., Any]) -> Callable[..., Any]:
    # allows us to use the decorator for async and non async functions
    if asyncio.iscoroutinefunction(f):

        @wraps(f)
        async def decorated(*args, **kwargs):
            result = await questionary.text("enter text").ask_async()
            # likely want to do something with the result here, or pass it to the wrapped function f
            return await f(*args, **kwargs)

        return decorated
    else:
        @wraps(f)
        def decorated(*args, **kwargs):
            result = questionary.text("enter text").ask()
            # likely want to do something with the result here, or pass it to the wrapped function f
            return f(*args, **kwargs)

        return decorated

# usage of decorator:
@universal_decorator
def my_sync_function():
    pass


@universal_decorator
async def my_async_function():
    pass
```

**Comment by davnat** [comment]
Maybe I'm missing something here, but I don't need a wrapper with both a sync and an async APIs: I only need the sync one.

The problem I'm facing is that the sync interface to questionary still uses an asyncio loop internally (from prompt-toolkit, I suppose), and it does not work if called inside an `async def` function, i. e. it's not really synchronous.

**Comment by layday** [comment]
prompt-toolkit always runs in a loop - you cannot divorce it from asyncio.  The question then becomes how do you await an async function from a synchronous function from inside the loop (i.e. from another async function) without calling `asyncio.run` or equivalent, and I don't think asyncio has that kind of facility.

**Comment by davnat** [comment]
@layday, if I understand correctly, you are saying that what I'd like to do cannot be done (without using additional tricks like [nest-asyncio](https://github.com/erdewit/nest_asyncio)).

In this case, I would suggest that maybe questionary (and prompt-toolkit) should only have an async API (and possibly some utilities to use it in sync code, because obviously the python world is mostly synchronous): I would find this much less confusing.

**Comment by layday** [comment]
> @layday, if I understand correctly, you are saying that what I'd like to do cannot be done (without using additional tricks like [nest-asyncio](https://github.com/erdewit/nest_asyncio)).

Well, trivially, you can run Questionary synchronously in a separate thread and prompt-toolkit will spawn a loop in that thread:

```py
import asyncio

import questionary


def question_wrapper():
    question = questionary.select(
        "What do you want to do?",
        choices=[
            "Order a pizza",
            "Make a reservation",
            "Ask for opening hours",
        ],
    )
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        return question.ask()
    else:
        return loop.run_in_executor(None, question.ask)


def ask_question_sync():
    return question_wrapper()


async def ask_question_async():
    return question_wrapper()


ask_question_sync()
asyncio.run(ask_question_async())

```

**Comment by kiancross** [comment]
I think @layday's last comment resolves this so I will close the issue. Please let me know if I am mistaken and I can reopen.

**Comment by lemassykoi** [comment]
I had to modify func in async to be able to use it in async:

```python
async def question_wrapper():
    question = questionary.text("User ==> ", multiline=True)
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        return question.ask()
    else:
        return await loop.run_in_executor(None, question.ask)
```

because it was not working in non async inside an async func.
Now I call it with `question = await question_wrapper()` and no problem.
