### ISSUE TITLE
Print an output line with question styling

### ISSUE THREAD

**Issue by BramVer** [tmbo/questionary#85]
I tried going through the README, issues, examples and code, but couldn't really find a way.  
It's a bit weird to have a question and input that's nicely styled, and then as soon as I need to print something (like a confirmation, or just extra information), it falls out of style.  

One could argue it's not in the scope of this project, but I believe it's related enough (and should be easy enough to implement with what's already here).

**Comment by tmbo** [comment]
That is a good point, but there are quite a number of libraries out there that allow to pretty print with color. An alternative would be to use promt-toolkit directly to print messages, which I think should be easy enough as well. If you provide a PR I'd say it is something we can add though 🙂

**Comment by BramVer** [comment]
Sorry for getting back to you so late.  
Yeah there are alternatives out there already, but then you'd have 2 libraries where one is to `say` and other to `ask` stuff.  
Getting the styling to be similar would be a timesink then as well :)  

Nice to see you've already been implementing this!
