### ISSUE TITLE
checkbox() bug - Single selection but many options with the same name

### ISSUE THREAD

**Issue by teaphi** [tmbo/questionary#91]
Single selection but many options with the same name
```python
import questionary
choices = []
for i in range(0,101):
    choices.append("choices")
questionary.checkbox("Checkbox!", choices)
```

**Comment by teaphi** [comment]
3. When displaying Chinese characters, the space between the circle and the Chinese characters disappears
```python
import questionary
questionary.checkbox("Display Chinese",["可","以","显","示","汉","字","吗","？"])
```
4. Use special methods to insert special characters (such as `Ctrl + V`,also,`Ctrl + V` will be displayed in blue)
```python
import questionary
questionary.checkbox("Display Chinese",["^V","^V","^V","^V","^V","^V","^V","^V"])
```

-- Translated by Google Translate

**Comment by kiancross** [comment]
Thanks for reporting these, @teaphi. It would be helpful to make separate issues for each report - then we can track them individually.

> 1. Single selection but many options with the same name

Thanks, I can reproduce this.

> 2. Text overlap

Can you describe the output that you are getting and the output you expect? When I run your example I see the following output:

![Screenshot from 2020-12-05 15-54-35](https://user-images.githubusercontent.com/11011464/101247629-92658d80-3712-11eb-9351-ac860b30b06a.png)

> 3. When displaying Chinese characters, the space between the circle and the Chinese characters disappears

I can't reproduce this. I think perhaps this could have something to do with the windows terminal (I am using Linux).

![Screenshot from 2020-12-05 16-00-14](https://user-images.githubusercontent.com/11011464/101247751-23d4ff80-3713-11eb-8e91-b0532980bab8.png)

> 4. Use special methods to insert special characters (such as Ctrl + V,also,Ctrl + V will be displayed in blue)

Again, I cannot reproduce this (see screenshot below). Perhaps again something to do with the Windows terminal.

![Screenshot from 2020-12-05 16-02-27](https://user-images.githubusercontent.com/11011464/101247848-947c1c00-3713-11eb-90b4-8e2d0bc5d872.png)

**Comment by teaphi** [comment]
> Thanks for reporting these, @teaphi. It would be helpful to make separate issues for each report - then we can track them individually.
> 
> > 1. Single selection but many options with the same name
> 
> Thanks, I can reproduce this.
> 
> > 1. Text overlap
> 
> Can you describe the output that you are getting and the output you expect? When I run your example I see the following output:
> 
> ![Screenshot from 2020-12-05 15-54-35](https://user-images.githubusercontent.com/11011464/101247629-92658d80-3712-11eb-9351-ac860b30b06a.png)
> 
> > 1. When displaying Chinese characters, the space between the circle and the Chinese characters disappears
> 
> I can't reproduce this. I think perhaps this could have something to do with the windows terminal (I am using Linux).
> 
> ![Screenshot from 2020-12-05 16-00-14](https://user-images.githubusercontent.com/11011464/101247751-23d4ff80-3713-11eb-8e91-b0532980bab8.png)
> 
> > 1. Use special methods to insert special characters (such as Ctrl + V,also,Ctrl + V will be displayed in blue)
> 
> Again, I cannot reproduce this (see screenshot below). Perhaps again something to do with the Windows terminal.
> 
> ![Screenshot from 2020-12-05 16-02-27](https://user-images.githubusercontent.com/11011464/101247848-947c1c00-3713-11eb-90b4-8e2d0bc5d872.png)


First of all, thank you very much for your reply.
For the second and third questions, I think you may need to move the cursor multiple times to reproduce it.
In addition, I have not tested these problems on Linux.

--Translated by Google Translate

**Comment by teaphi** [comment]
I have split the first three questions. They are #91 , #92 , #93 (the fourth problem should be a Windows problem, so there is no split).

Thanks again!

--Translated by Google Translate

**Comment by kiancross** [comment]
Thanks - I can reproduce this one.

**Comment by kiancross** [comment]
A smaller broken example:

```python3
import questionary

questionary.checkbox("Choices", [
    questionary.Choice("Foo"),
    questionary.Choice("Foo")
]).ask()
```

Having a look at this bug at the moment.

**Comment by kiancross** [comment]
@teaphi If you would like choices with the same titles, you can do this:

```python3
import questionary

questionary.checkbox("choices", [
    questionary.Choice(title="Foo", value="foo1"),
    questionary.Choice(title="Foo", value="foo2")
]).ask()
```

They can be selected individually.

`title` is the text that is displayed to the user, whereas `value` is the key used internally to differentiate options (so must be different).
