### ISSUE TITLE
Checkbox prompt text overlaps on Windows

### ISSUE THREAD

**Issue by teaphi** [tmbo/questionary#92]
Text overlap
```python
import questionary
choices = []
for i in range(0,101):
    choices.append(str(i))
questionary.checkbox("Checkbox!", choices)
```
![GIF 2020-12-6 7-43-32.gif](https://i.loli.net/2020/12/06/1nW8aAsRg45hqcr.gif)

**Comment by kiancross** [comment]
Cannot reproduce this on Linux - potentially a bug isolated to Windows.

**Comment by kiancross** [comment]
@teaphi Which version of prompt_toolkit are you using?

**Comment by HelloGwkki** [comment]
@kiancross 3.0.8

**Comment by YashDjsonDookun** [comment]
I assume this has been fixed since I can't seem to replicate this issue on my windows machines.
I believe this can be closed. 👍

**Comment by kiancross** [comment]
@YashDjsonDookun Which version of prompt toolkit are you using? I will double check on Windows tonight too.

**Comment by beliaev-maksim** [comment]
@tmbo 
cannot be reprdocued on latest master

**Comment by tmbo** [comment]
Sounds great, let’s close this then 🎉
